# Generated by Django 4.1.7 on 2023-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadlines',
            field=models.DateField(default="2003-10-11", verbose_name='Сроки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.CharField(default="0", max_length=15, verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
